### ISSUE TITLE
SKOS concept schemes should contain top concepts

### ISSUE THREAD

**Issue by marie-ototoi** [DOREMUS-ANR/knowledge-base#1]
- Either as a property of the ConceptScheme using [skos:hasTopConcept](https://www.w3.org/2009/08/skos-reference/skos.html#hasTopConcept)
- or as a property of the Concept using [skos:topConceptOf](https://www.w3.org/2009/08/skos-reference/skos.html#topConceptOf)

If possible, the second option is preferred for display in VIZSKOS.
- [x] Derivation --> all nodes are TopConcepts
- [x] Genre --> all nodes are TopConcepts
- [x] Keys --> all nodes are TopConcepts
- [x] IAML --> Solve #2 and then the broadest are TopConcepts
- [x] Mode --> Already written on the concept

**Comment by marie-ototoi** [comment]
Note: `skos:topConceptOf` is a specific property of `skos:inScheme`, no need to have both when it's a TopConcept

**Comment by pasqLisena** [comment]
If there is no hierarchy, everything is a TopConcept-s. Updated the description of the issue.

**Comment by pasqLisena** [comment]
I close this because it was already solved
