### ISSUE TITLE
Publier les référentiels en json-ld pour faciliter la consommation par vizskos

### ISSUE THREAD

**Issue by marie-ototoi** [DOREMUS-ANR/knowledge-base#10]
Vizskos prend du json-ld en entrée, il peut le récupérer dans le sparql endpoint quand les référentiels seront publiés, ou bien charger un fichier de fallback

**Comment by rtroncy** [comment]
Les données des référentiels sont déjà chargées dans le SPARQL endpoint. Exemple (trouver tous les concepts dans le référentiel des genres) [résultats](http://data.doremus.org/sparql?default-graph-uri=&query=select+%3Fs+%3FprefLabel+%3FaltLabel+%0D%0Awhere+%7B+%0D%0A+%3Fs+a+skos%3AConcept+.%0D%0A+%3Fs+skos%3AinScheme+%3Chttp%3A%2F%2Fdata.doremus.org%2Fvocabulary%2Fgenre%3E.%0D%0A+%3Fs+skos%3AprefLabel+%3FprefLabel+.%0D%0A+%3Fs+skos%3AaltLabel+%3FaltLabel+.%0D%0A%7D%0D%0Agroup+by+%3Fs%0D%0ALIMIT+50%0D%0A&format=text%2Fhtml&timeout=0&debug=on):

```
select ?s ?prefLabel ?altLabel 
where { 
 ?s a skos:Concept .
 ?s skos:inScheme <http://data.doremus.org/vocabulary/genre>.
 ?s skos:prefLabel ?prefLabel .
 ?s skos:altLabel ?altLabel .
}
group by ?s
LIMIT 50
```

On pourrait matérialiser les référentiels complets en JSON-LD pour t'aider.

**Comment by pasqLisena** [comment]
Hello @marie-ototoi,
I materialized the vocabularies.

Example:
http://data.doremus.org/vocabulary/key

Setting the `Accept` HTTP Header you can select the format.

Example:

```
HTTP GET http://data.doremus.org/vocabulary/key
Accept: application/ld+json
```

Is it enough? If yes, close the issue please :)

**Comment by rtroncy** [comment]
@pasqLisena Does your deployment script re-materialize the vocabularies in json-ld after each deployment (or when the vocabularies are changed)?

**Comment by pasqLisena** [comment]
Yes, it is just a setting of Virtuoso
