### ISSUE TITLE
[Radio France] Convert musical genres and instruments in SKOS for the alignment

### ISSUE THREAD

**Issue by rtroncy** [DOREMUS-ANR/knowledge-base#15]
In both cases, a spreadsheet is provided so OpenRefine can be used.
* Musical Genres: the source data is at https://drive.google.com/file/d/0B_6mSQxUBpLoU014MUg2Z2QxcTg/view. I suggest to use the URI pattern: http://data.doremus.org/vocabulary/rf/genre
* Instruments: the source data is at https://drive.google.com/file/d/0B_6mSQxUBpLoc1ZvMmhqMGtQVms/view. I suggest to use the URI pattern: http://data.doremus.org/vocabulary/rf/mop

**Comment by rtroncy** [comment]
Sémantique genres et instruments :
-  DE (Descripteur) ... ```skos:prefLabel```
-  TG : Terme Générique ... ```skos:broader```
-  TS : Terme Spécifique ... ```skos:narrower```
(il y a donc TG et TS (en symétrie) pour re-créer la hiérarchie)
-  Synonyme : ```skos:altLabel``` (quand il y en a plusieurs, ils sont sur plusieurs lignes de la colonne D et le prefLabel n’est pas répété dans la colonne A)
-  VA = Voir Aussi : ```skos:related```
-  NA : note descriptive du genre ou de l’instrument ... ```skos:editorialNote```

Non ce n’est pas la peine d’inclure les termes à ne plus utiliser
Il y a effectivement très très peu de hiérarchie dans le thésaurus des instruments. Ce n’est pas la peine de tenir compte du peu qu’il y a.
Le $ de la cellule C19 est un séparateur entre différents termes. Pour les TS, peu importe puisqu’on ne tient pas compte de la hiérarchie mais attention, tu en trouves aussi dans la colonne E pour les VA (E 1412, E 2269…)
Pour les instruments et essentiellement pour les instruments « du monde », on a effectivement rajouté une notion géographique (PAYS), pour dire en gros d’où ils viennent, à quelle culture ils sont associés…   ; il y a quelques années, Jean avait fait une formation web sémantique à RF et on avait pris comme exemple de travail ce thésaurus. Pour ces valeurs géographiques, on avait utilisé ```dcterms:coverage```

**Comment by pasqLisena** [comment]
closed in e6d00b4b04a8dcc2c17f6ef91bf07f998ee33e40 and 33ebd7a9563cb015d9ec69ed822a14a3cb813fc9
