### ISSUE TITLE
[Rameau] Re-construct a single Genre controlled vocabularies from RAMEAU

### ISSUE THREAD

**Issue by rtroncy** [DOREMUS-ANR/knowledge-base#20]
The idea is to get a single SKOS file (encoded in Turtle) containing the useful concepts describing musical genres that come from [RAMEAU](http://rameau.bnf.fr/informations/produits.htm#rameauformatrdfskos).

Sources:
* An excel file prepared by Frédéric containing 684 terms, see https://drive.google.com/file/d/0B5xduP7QwIkOcTlSVnVfdVR2b3c/view
* An excel file prepared by Frédéric containing 288 true alignments between IAML and RAMEAU, see https://drive.google.com/file/d/0B5xduP7QwIkOLVZjZldCaTJhelE/view
* The pattern to get the SKOS description of each concept is to GET 'http://data.bnf.fr/' + numerical_id + forme_retenue (lowercasing + replacing white space by _) in order to get the ARK identifier

**Comment by pasqLisena** [comment]
If it can be useful, there is already a NodeJS [script](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/scripts/rameau-groups-script.js) that i used to perform a similar task.

Briefly, it read a [csv](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/raw-data/rameau.groups.txt) (trivial conversion of the excel files) and read the code from each line.
The code is then used for querying http://data.bnf.fr/sparql. The only difference is that in our tables the code contain a prefix `FRBNF` that should be removed.

**EXAMPLE** for the first line: `FRBNF16962284` - "Acid House" - [results](http://data.bnf.fr/sparql?default-graph-uri=&query=SELECT+*%0D%0AWHERE+%7B%0D%0A+++%3FidArk+bnf-onto%3AFRBNF+%2216962284%22%5E%5Exsd%3Ainteger%3B%0D%0A++++%3Fp+%3Fo%0D%0A%7D%0D%0A&format=text%2Fhtml&timeout=0&should-sponge=&debug=on)
```sparql
SELECT *
WHERE {
   ?idArk bnf-onto:FRBNF "16962284"^^xsd:integer;
    ?p ?o
}
```

It save the collected data as SKOS:collection (see [output](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/rameau.groups.ttl)), but it can be adapted.

**Comment by manoach** [comment]
In the generated vocabulary [rameau.genres.ttl](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/rameau.genres.ttl), there are only 670 terms because in the [excel file](https://drive.google.com/file/d/0B5xduP7QwIkOcTlSVnVfdVR2b3c/view) there are:

- 1 blank row;
- 13 genres without BNF identifier:
Bombas
Norteño (musique)
Octuors de jazz 
Old time (musique)
Opéras télévisés 
Pub-rock 
R'n'B contemporain 
Riot grrrl 
Rock psychédélique 
Ska-punk 
Taqsim
Thayambaka
Trance

**Comment by rtroncy** [comment]
Thanks for the investigation @manoach. We will ask Frédéric to further complete the Excel sheet (provide the 13 missing ark) during this week DOREMUS meeting

**Comment by pasqLisena** [comment]
@manoach have you committed the final script for the generation of rameau.genres.ttl ?
I am trying the one in the script folder (rameau-genre-script.js) but I think that it is not the last version.

**Comment by manoach** [comment]
@pasqLisena, yes, I did it. After running [rameau-genre-script.js](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/scripts/rameau-genres-script.js), the [genres-rameau-post-script](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/scripts/genres-rameau-post-script.js) must be executed for rebuilding the URIs.

**Comment by pasqLisena** [comment]
Ok, now I see.

We should have an agreement on the uri policy because they are not coherent:
* For [genres](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/rameau.genres.ttl) is `http://data.doremus.org/vocabulary/rameau/genre/<label>`
* For [mop](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/mop-rameau.ttl) is `http://data.bnf.fr/ark:/12148/<ark_number>`

**Comment by rtroncy** [comment]
If the dump is an exact subset of the RAMEAU dump, and if we are not adding any new statements, then we should not mint new URIs for those concepts. I would therefore keep [mop](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/mop-rameau.ttl) like this and modify the genre thesaurus and not creating new URIs to identify existing concepts but re-use ark identifier. Between, the filename should be ```genre-rameau.ttl```

**Comment by manoach** [comment]
In the [alignements file](https://drive.google.com/file/d/0B5xduP7QwIkOLVZjZldCaTJhelE/view) there are:

- 1 concept from RAMEAU without BNF identifier : [**_Gagaku_**]

- 1 concept [**_Boogie-woogie_**] with a BNF identifier (**12290265**) but without ARK identifier. The SPARQL query gives no [result](http://data.bnf.fr/sparql?default-graph-uri=&query=SELECT+%3FidArk%0D%0AWHERE+%7B%0D%0A+++%3FidArk+bnf-onto%3AFRBNF+%2212290265%22%5E%5Exsd%3Ainteger%0D%0A%7D&format=text%2Fhtml&timeout=0&should-sponge=&debug=on)

```
SELECT ?idArk
WHERE {
   ?idArk bnf-onto:FRBNF "12290265"^^xsd:integer
}
```

**Comment by kgtodorov** [comment]
@manoach the genre-rameau vocabulary appears to have a problem. We have for all entities

  <http://data.bnf.fr/ark:/12148/cb11963474g> a skos:Concept ;
          rdfs:seeAlso <http://catalogue.bnf.fr/ark:/12148/cb11963474g> ;
          = <http://stitch.cs.vu.nl/vocabularies/rameau/ark:/12148/cb11963474g> ;
while we just need a comma instead of "; = ".

**Comment by pasqLisena** [comment]
> http://data.bnf.fr/ark:/12148/cb11963474g a skos:Concept ;
rdfs:seeAlso http://catalogue.bnf.fr/ark:/12148/cb11963474g ;
= http://stitch.cs.vu.nl/vocabularies/rameau/ark:/12148/cb11963474g ;
while we just need a comma instead of "; = ".


The fact is that `=` is a short form for `owl:sameAs` in Turtle.

**Comment by kgtodorov** [comment]
> The fact is that = is a short form for owl:sameAs in Turtle.

Yeah but seems that Jena is not supporting this shortcut. 

"Fail Loading files in Jena: com.hp.hpl.jena.n3.turtle.TurtleParseException: Line 18, column 5: = (owl:sameAs) not legal in Turtle"

**Comment by rtroncy** [comment]
@kgtodorov Change your turtle parser ;-)

**Comment by pasqLisena** [comment]
Well, it is a trivial modification, we can do it :)
I had the same problem of Konstantin also.

**Comment by rtroncy** [comment]
Can this issue be closed now?

**Comment by pasqLisena** [comment]
yes
