### ISSUE TITLE
Create MODS of Catalogs

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#21]
We should create the MODS of Catalog Names starting from the [spreadsheet](https://docs.google.com/spreadsheets/d/1BaluYvqmCTI04ALpiyobjbKWOb2k8KKa04VqasL4xL0/edit#gid=0).

**Comment by pasqLisena** [comment]
Some lines in the spreadsheet (43 + 44 and 87 + 88) refers to **different version of the same catalog**.

**How should we manage them?** Some options:
1. Model them as a single `ModsResource`
2. Link them with one of the following properties:
    1. [modsrdf:relatedSucceeding](http://www.loc.gov/standards/mods/rdf/v1/#relatedSucceeding) - Relates the described resource to a another MODS resource which suceeded it. 
    2. [modsrdf:relatedVersion](http://www.loc.gov/standards/mods/rdf/v1/#relatedVersion) - Relates the described MODS resource to another MODS resource which is a different version of the described resource. 
    3. [modsrdf:relatedReview](http://www.loc.gov/standards/mods/rdf/v1/#relatedReview) - Relates the described MODS resource to another MODS resource which is review of the described resource. 
    4. [modsrdf:relatedOriginal](http://www.loc.gov/standards/mods/rdf/v1/#relatedOriginal) - Relates the described MODS resource to another MODS resource which is an original of the described resource.

**In the mapping**, which version should we use for the linking to the vocabulary? I think that the **most recent one** is a good choice.

**Comment by pasqLisena** [comment]
Things missing in the spreadsheet that I found in the data (and in wikipedia):

* Kobylanska catalog has identifier `KK` - see [wikipedia](https://en.wikipedia.org/wiki/Mazurkas_(Chopin)#List_of_mazurkas)
* Kochel catalog for Mozart has double identifier `KV` and `K` - see [wikipedia](https://en.wikipedia.org/wiki/Köchel_catalogue)
* Charpentier catalog has identifier `H` - see [wikipedia](https://fr.wikipedia.org/wiki/Marc-Antoine_Charpentier?oldformat=true#Catalogue_complet)
* Ryom catalog has sometimes identifier `R` instead of `RV` - see [wikipedia](https://fr.wikipedia.org/wiki/Catalogue_Ryom?oldformat=true)
* There are multiple catalogs for Scarlatti's works (instead we have only one) - see [wikipedia](https://en.wikipedia.org/wiki/List_of_solo_keyboard_sonatas_by_Domenico_Scarlatti?oldformat=true)
* Breitkopf und Härtel catalog has identifier `MVW`-- see [wikipedia](https://en.wikipedia.org/wiki/Mendelssohn-Werkverzeichnis?oldformat=true)

Instead sometimes the MARC data are dirty:
* Some Carl Bach works use identifier `W` instead of `Wq` - see [example](http://data.doremus.org/expression/7d8afd78-bb42-33a6-985e-c7f17a31af86)
* Some Schütz works use identifier `SW` instead `SWV` - see [example](http://data.doremus.org/expression/438739a2-b2ef-3250-bb67-7805f41d3209)

**Comment by rtroncy** [comment]
Can we rather use `mods` instead of `modsrdf` as prefix for `<http://www.loc.gov/standards/mods/rdf/v1/#>` ?

The value of ```dcat:accessURL``` should probably be updated afterwards with the real URI where the vocabulary will be deployed rather than using the rawgit pattern

**Comment by pasqLisena** [comment]
> Can we rather use `mods` instead of `modsrdf` as prefix for `<http://www.loc.gov/standards/mods/rdf/v1/#>` ?

Yes, we can but the default prefix is `modsrdf` (see documentation at http://www.loc.gov/standards/mods/rdf/v1/# ).

**Comment by rtroncy** [comment]
OK, forget what I said :-) I should have checked. MODS is **not** in LOV :-(

**Comment by pasqLisena** [comment]
> In the mapping, which version should we use for the linking to the vocabulary?

 - [ ] for Mozart, try to map also with titles/opus number using [wikipedia](https://fr.wikipedia.org/wiki/Catalogue_K%C3%B6chel?oldformat=true)
- [ ] for Debussy, it is always the last one

> Management of catalog version.

- [x] Use `mods:relatedVersion`

> Things missing in the spreadsheet that I found in the data (and in wikipedia):

- [x] Add them in the vocabulary

> Instead sometimes the MARC data are dirty:

- [x] Consider if there is a property like "alternateIdentifier"
- [x] Add them in the vocabulary
 
see also https://docs.google.com/document/d/12MOgxQwn3OkTJsc4b1YL5nxJlXtNXMNIUwargxSWGOU/edit
