### ISSUE TITLE
Validation des alignements des genres musicaux

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#22]
Realise a Turtle file that contains the validated "exactMatch" between the musical genres

## RoadMap
- [x] @kgtodorov Produce and validate the alignments

**Comment by kgtodorov** [comment]
@pasqLisena In the skosification process, I think it is preferable not to include the "&" character in the URIs, as is the case for the "r&b" genre in diabolo and redomi unless it is encoded. Or else, simply use "rnb" instead of "r&b" for the genre URIs.

**Comment by pasqLisena** [comment]
> In the skosification process, I think it is preferable not to include the "&" character in the URIs, as is the case for the "r&b" genre in diabolo and redomi unless it is encoded. Or else, simply use "rnb" instead of "r&b" for the genre URIs.

I see, I will change it in the next export (very soon).

**Comment by rtroncy** [comment]
This calls for a generic strategy to handle special characters in URIs. How many cases do we have? Is the ampersand the only case? How many special characters are being used?
For ampersand, I would prefer we replace the ```&``` by ```and``` rather than ```n```

**Comment by kgtodorov** [comment]
> This calls for a generic strategy to handle special characters in URIs.

Agreed.

> For ampersand, I would prefer we replace the & by and rather than n

Well, the commonly accepted written reference to this particular genre is RnB just like one often writes Rock'nRoll or Rhythm'nBlues (https://fr.wikipedia.org/wiki/Rhythm_and_blues). Once we have the inventory of special characters we can decide.

**Comment by rtroncy** [comment]
> Well, the commonly accepted written reference to this particular genre is RnB just like one often writes Rock'nRoll or Rhythm'nBlues (https://fr.wikipedia.org/wiki/Rhythm_and_blues). Once we have the inventory of special characters we can decide.

Yes for the labels, but look at what wikipedia is doing in its url :-)

**Comment by kgtodorov** [comment]
> Yes for the labels, but look at what wikipedia is doing in its url :-)

Oh yes! Beautiful example. :)

**Comment by kgtodorov** [comment]
And a counter one  https://fr.wikipedia.org/wiki/RnB_contemporain.

**Comment by pasqLisena** [comment]
Doubt.

I think that the resulting unified vocabulary (let's consider the genre one as example), should contain:
- all the concept of the pivot (in this case IAML), with all its properties
- the concepts from the other vocabularies, taking care that concepts with `exactMatch` should be taken only once
- all the labels that are not `prefLabel`
- the value of `prefLabel` of the `exactMatch` ones (not pivot) as `altLabel` on the matched concept ... or not?

**Comment by rtroncy** [comment]
Yes, we can add more ```skos:altLabel``` using all labels of the concepts that have been exact matched. I confirm all other points
