### ISSUE TITLE
Metadata of Vocabularies

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#24]
We should add metadata to our vocabularies. In particular:
- `dct:creator` : `http://data.doremus.org/organization/DOREMUS` (add it on the [organization file](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/data/organization.ttl))
- `dct:modified` : date of today
- `rdfs:label` where missing

**Comment by rtroncy** [comment]
+1 for creating an URI in our namespace to identify the organization and to add more information such as the ```foaf:homepage``` of the organization.

**Comment by rtroncy** [comment]
Has the metadata been systematically added to all our vocab? Can we close this issue?

**Comment by pasqLisena** [comment]
The metadata has not been added to the vocabulary that already existed as SKOS (RAMEAU and MIMO)
