### ISSUE TITLE
Blank node are doubled in the triple store

### ISSUE THREAD

**Issue by delahousse** [DOREMUS-ANR/knowledge-base#25]
Hello
when retrieving data about "sonate au clair de lune" we noticed all rdf triples are doubled for blank nodes.
see file attached
[RDF graph_Musical composition_NATIF.txt](https://github.com/DOREMUS-ANR/knowledge-base/files/803470/RDF.graph_Musical.composition_NATIF.txt)

**Comment by pasqLisena** [comment]
Thanks for raising this issue :)

This bug is already solved in the code, and will be available online in the next release of data.
