### ISSUE TITLE
M15_Dedication and M15_DedicationStatement

### ISSUE THREAD

**Issue by delahousse** [DOREMUS-ANR/knowledge-base#27]
Hello
In the graph we find class M15_Dedication and in the doremus owl file M15_Dedication_Statement
Can you unify and confirm the use of one or the other ?

**Comment by pasqLisena** [comment]
Hello @delahousse,
yes, it is a recent change in the ontology naming. There are few additional ones, and all are already in sync with `marc2rdf`. Next release of data will fix this problem
