### ISSUE TITLE
P82_at_sometime_within: difficulty in making sparql query

### ISSUE THREAD

**Issue by delahousse** [DOREMUS-ANR/knowledge-base#28]
Do you know how we can query property `ecrm:P82_at_some_time_within	"18010101/18011231"^^dct:W3CDTF` ? For example to find all musical works created in the year 1801 ? or to find all musical works created on 3/10/1801 ?

Is is a good idea to use `dct:W3CDTF` format ?

Below an example:
```turtle
<http://data.doremus.org/event/3f9d2fae-da75-3c66-902d-fa3a0755d892>
	rdf:type	efrbroo:F28_Expression_Creation ;
	efrbroo:R17_created	<http://data.doremus.org/expression/d72301f0-0aba-3ba6-93e5-c4efbee9c6ea> ;
	efrbroo:R19_created_a_realisation_of	<http://data.doremus.org/work/30256b51-d277-3688-ad62-560ae982ff2f> .
	ecrm:P9_consists_of
		[	mus:U31_had_function_of_type	"compositeur"@fr ;
			ecrm:P14_carried_out_by	<http://data.doremus.org/artist/6963af5e-b126-3d40-a84b-97e0b78f5452> ] ;
	ecrm:P4_has_time-span	[ecrm:P82_at_some_time_within	"18010101/18011231"^^dct:W3CDTF ] .
```

**Comment by pasqLisena** [comment]
We already had exactly this doubts last week with @rtroncy, having the same difficulties.
We consequently modified the representation of time spans.

Here you can find an example of how Time Spans look like now (next release):

```turtle
<http://data.doremus.org/event/1a08e145-8ee5-38f4-a618-5ccd24c6e818>
        a                      efrbroo:F28_Expression_Creation ;
        ecrm:P4_has_time-span  <http://data.doremus.org/event/1a08e145-8ee5-38f4-a618-5ccd24c6e818/time> ;
        ecrm:P9_consists_of    <http://data.doremus.org/event/1a08e145-8ee5-38f4-a618-5ccd24c6e818/activity/1> ;
        efrbroo:R17_created    <http://data.doremus.org/expression/9338f647-cb65-3457-abbe-85c11385736b> ;
        efrbroo:R19_created_a_realisation_of
                <http://data.doremus.org/work/7e255005-2e8f-3166-81a4-e18ec635be42> .

<http://data.doremus.org/event/1a08e145-8ee5-38f4-a618-5ccd24c6e818/time>
        a                             ecrm:E52_Time-Span ;
        rdfs:label                    "1917/1923" ;
        ecrm:P79_beginning_is_qualified_by
                "1917-01-01"^^xsd:date ;
        ecrm:P80_end_is_qualified_by  "1923-12-31"^^xsd:date .

<http://data.doremus.org/event/1a08e145-8ee5-38f4-a618-5ccd24c6e818/activity/1>
        a                             ecrm:E7_Activity ;
        mus:U31_had_function_of_type  "compositeur"@fr ;
        ecrm:P14_carried_out_by       <http://data.doremus.org/artist/bcfefeca-ab42-3e86-9ffa-0b0176319b29> .

<http://data.doremus.org/artist/bcfefeca-ab42-3e86-9ffa-0b0176319b29>
        a                           ecrm:E21_Person ;
        ecrm:P100i_died_in          "1974"^^xsd:gYear ;
        ecrm:P131_is_identified_by  "Milhaud, Darius (1892-1974)" ;
        ecrm:P98i_was_born          "1892"^^xsd:gYear ;
        foaf:firstName              "Darius" ;
        foaf:name                   "Darius Milhaud" ;
        foaf:surname                "Milhaud" .
```

**Comment by pierrechoffe** [comment]
@pasqLisena careful, careful : in CRM the properties _P79 beginning is qualified by_ and _P80 end is qualified by_  are not supposed to be used this way. The range is explicitly a string and the scope note states _"This property qualifies the beginning of an E52 Time-Span in some way. The nature of the qualification may be certainty, precision, source etc"._

The example is : 
the time-span of the Holocene (E52) beginning is qualified by approximately (E62)

**Comment by pasqLisena** [comment]
> The example is :

This example is not so clear, there are some example in RDF / TTL / JSON-LD ?
It is very difficult to find how others use them for real.

**Comment by delahousse** [comment]
Yes, but when CRM is not really usable for sparql queries of the graph it is a real problem.
We could go back to CRM team to explain our use case about querying data, which is quite a good use case for open data publication.
We also could have two representations of the same data, one to be conform with CRM but the data is not really usable, and one to be able to process the data... but it is quite confusing.
We could check how British Museum implemented this property with CRM

@pasqLisena: the example you give with your new solution are not implemented in the graph yet ? when will it be accessible ?

**Comment by pasqLisena** [comment]
> when will it be accessible ?

I hope to put everything up for the beginning of the next week.

> We could check how British Museum implemented this property with CRM

They are currently using deprecated properties of CRM.

**Comment by rtroncy** [comment]
I'm also in favor of a pragmatical interpretation of the CRM properties which are then usable. Note @pierrechoffe that date (as defined in XML Schema) are strings too thus we are not violating the ontology (formally).

**Comment by pierrechoffe** [comment]
@rtroncy you know better :) but aren't there any generic rdf properties that could be used ?

**Comment by delahousse** [comment]
It's what Raphael and Pasquale did in fact
It s CRM which does not conform to best practices

**Comment by delahousse** [comment]
Perfect
Tell us

**Comment by delahousse** [comment]
Salut

xsd:gYear, xsd:date... sont des troncatures de xsd:dateTime
https://www.w3.org/TR/xmlschema-2/#isoformats

Dans Protégé seul xsd:dateTime est disponible comme datatype.

Dans le cadre de l'ontologie juridique de l'Europe on s'était déjà posé
cette question de format de date et finalement nous avons utilisé
xsd:dateTime partout. L'utilisation de xsd:dateTime permettant de décrire
des dates/heures, des dates, des années...

Qu'en pensez vous ?

**Comment by pasqLisena** [comment]
I see @delahousse, however we almost never have times. Do not you think that we add "weight" to the data in this way?

**Comment by delahousse** [comment]
I know, in the other project it was the same, but at the end, and I don't have all the rationales, we sticked with dateTime.
If we choose to use date, will will have to introduce this datatype in Protégé. I will try to find the rationales from this project.

**Comment by delahousse** [comment]
Dans la nouvelle base il y a des changements dans la gestion des dates, j'ai qq remarques.

* pour la propriété P198i_was_born on a une valeur 1770-01-01, ce qui n'est pas la date de naissance mais la désignation de 1770. Je pense qu'il est plus propre et accepté par le format dateTime d'indiquer 1770 qui indique bien l'interval de l'année 1770. Dans le cas contraire on aura du mal a savoir qui est vraiment né le 1770-01-01
* pour la création d'une oeuvre on utilise E52_Timespan avec les propriétés P79 beginning is qualified by valeur 1801-01-01 et P80 end is qualified by 1801-12-31. C'est juste d'un point de vue connaissance, c'est bien dans cet interval avec un début et une fin, mais si on pouvait utiliser une propriété qui aurait comme valeur 1801 ce serait plus pratique. L'ontologie Time supporte bien cette gestion des intervalles ou l'on indique soit une année, soit une vraie date de début et fin.

**Comment by pasqLisena** [comment]
> property P98i_was_born

It is weird. Basically in the [Virtuoso visualization](http://data.doremus.org/artist/40e88279-dc12-3dd0-8aeb-3b8dd41af302) we see `"1934-01-01"^^xsd:dateTime` while in the [rdf data](http://data.doremus.org/sparql?query=define%20sql%3Adescribe-mode%20%22CBD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdata.doremus.org%2Fartist%2F40e88279-dc12-3dd0-8aeb-3b8dd41af302%3E&output=text%2Fturtle) we have `"1934"^^xsd:year`. 
@rtroncy did you ever see this behavior?

> E52_Timespan

The fact is that we should manage the situation in which we have not a whole year as span (one month, few days, one day, etc.). Ok for finding a new solution, but this one for now ensure that we write the query in the same way for each situation.

**Comment by delahousse** [comment]
I propose to use the type dateTime for all date independently of the granularity (year month date and time). I thing this is well documented in the time ontology and to have a universal way to describe more complex interval. We could have a time about this at the AG or before based on a previous study of the subject

We need to have expression of time / date which work with heterogeneous info coming from each provider

**Comment by rtroncy** [comment]
> It is weird. Basically in the Virtuoso visualization we see "1934-01-01"^^xsd:dateTime while in the rdf data we have "1934"^^xsd:year.
@rtroncy did you ever see this behavior?

What you meant is that a ```xsd:gYear``` in the RDF data is converted into a ```xsd:dateTime``` once loaded in Virtuoso? This would not be the first time it happens. For example, Virtuoso is already changing the geosparql datatype into a built-in specific virtuoso one for historical reason (see the [issue](https://github.com/openlink/virtuoso-opensource/issues/456) I have raised). However, regarding xsd datatype, such an issue has never been raised and ```xsd:gYear``` is used a lot in DBpedia.

@delahousse Why don't you want to use the set of datatypes defined in XML Schema (gMonth, gYear, etc.)? They are all dateTime anyway and SPARQL knows how to compare them.

**Comment by delahousse** [comment]
I am fine to use gMonth, gYear..
We will do more query on the database today as working for the training tool, will if every thing is fine when we query dates.
Have a good day
jean

**Comment by pasqLisena** [comment]
> What you meant is that a xsd:gYear in the RDF data is converted into a xsd:dateTime once loaded in Virtuoso? 

Not exactly, the data in the db is good, it is more a problem of visualization (see the links on my last comment).

**Comment by rtroncy** [comment]
Ah! But then we don't care about what Virtuoso displays in the automatically generated HTML pages. What matters is what people GET out of the knowledge base.

I believe we still need to alter the conversion (mard2rdf) process. I erroneously suggested you before to approximate a year (e.g. 1905) into a date (e.g. 01/01/1905). We should instead use the full list of xsd datatype, so a ```xsd:gYear``` in this case.

**Comment by pasqLisena** [comment]
> I erroneously suggested you before to approximate a year (e.g. 1905) into a date (e.g. 01/01/1905). We should instead use the full list of xsd datatype, so a xsd:gYear in this case.

I have the doubt that is not completely clear how we manage dates.
Basically we have this situation for artists:
```turtle
<http://data.doremus.org/artist/6963af5e-b126-3d40-a84b-97e0b78f5452> a ecrm:E21_Person ;
    ecrm:P131_is_identified_by "Beethoven, Ludwig van (1770-1827)" ;   
    ecrm:P100i_died_in "1827"^^xsd:gYear ;
    ecrm:P98i_was_born "1770"^^xsd:gYear .
```

For works (Expression Creation) we declare everything with a start and an end:
1. it covers a year

```turtle
<http://data.doremus.org/event/b3588ac3-eaf2-3de4-a91b-ddd51824aab1> a efrbroo:F28_Expression_Creation ;
ecrm:P4_has_time-span [ a ecrm:E52_Time-Span ;
      rdfs:label "1802" ;
      ecrm:P79_beginning_is_qualified_by "1802-01-01"^^xsd:date ;
      ecrm:P80_end_is_qualified_by "1802-12-31"^^xsd:date .
  ]
```

2. less trivial periods
```turtle
<http://data.doremus.org/event/51f091c4-ddd5-3af0-9ac7-8fcc9bfd845a> a efrbroo:F28_Expression_Creation ;
ecrm:P4_has_time-span [ a ecrm:E52_Time-Span ;
      rdfs:label "1939-08-05/1939-08-30" ;
      ecrm:P79_beginning_is_qualified_by "1939-08-05"^^xsd:date ;
      ecrm:P80_end_is_qualified_by "1939-08-30"^^xsd:date .
  ]
```

**_We should change this behavior?_**

p.s. we have not the blank node there, I put it for readability

**Comment by rtroncy** [comment]
For artists, don't forget to add a ```rdfs:label``` to the ```ecrm:E21_Person```. The birth / death date is correct, using a ```xsd:gYear``` when we only now the year OR using a ```xsd:date``` when we have the precise day/month/year information.

For works (expression creation), indeed, we should always use a ```ecrm:E52_Time-Span```. I suggest we also vary the values of ```ecrm:P79_beginning_is_qualified_by``` and ```ecrm:P80_end_is_qualified_by``` by using either a precise ```xsd:date``` when we know it OR a ```xsd:gYear``` when we just have the year information. One check that is needed, though, is that two timespans using respectively ```xsd:date``` and ```xsd:gYear``` are comparable, e.g. sortable! I believe this is the case, but Virtuoso always leaves surprise.

Finally, in the ontology, we can declare that the range of those properties is ```xsd:dateTime``` which is the most generic datatype from which ```xsd:date```, ```xsd:gYear```, etc. are derived from.

**Comment by pasqLisena** [comment]
> For artists, don't forget to add a ```rdfs:label``` to the ```ecrm:E21_Person```.

Yes, it is done. This is an extract 😄 .

> One check that is needed, though, is that two timespans using respectively ```xsd:date``` and ```xsd:gYear``` are comparable, e.g. sortable! I believe this is the case, but Virtuoso always leaves surprise.

Ok I double check it.

**Comment by delahousse** [comment]
I support all those proposals about date management

Jean

**Comment by rtroncy** [comment]
>>  One check that is needed, though, is that two timespans using respectively xsd:date and xsd:gYear are comparable, e.g. sortable! I believe this is the case, but Virtuoso always leaves surprise.

> Ok I double check it.

@pasqLisena Did you check it? Can we close this issue?

**Comment by pasqLisena** [comment]
It seems that they are comparable. I checked with the following query:
```sparql
SELECT DISTINCT ?artist ?name ?born where { 
  ?artist ecrm:P98i_was_born ?born ; foaf:name ?name.
  ?activity ecrm:P14_carried_out_by ?artist .
  FILTER ( ?born >= "1700-01-01"^^xsd:date AND ?born < "1800-01-01"^^xsd:date )
} ORDER BY ?born
```

> ... using either a precise xsd:date when we know it OR a xsd:gYear when we just have the year information.

I will close it when I will implement this rule.

**Comment by pierrechoffe** [comment]
@pasqLisena can we discuss this point tomorrow ? in addition to the above, CRM dates are more flexible now, we may use E50 Date "1850" like so: 
```
F28 Expression Creation P4 has time-span E52 Time-Span P78 is identified by E50 Date "1850"
```
i.e.
```
<http://data.doremus.org/event/b3588ac3etc> a efrbroo:F28_Expression_Creation ;
      ecrm:P4_has_time-span [ a ecrm:E52_Time-Span ;
      rdfs:label "1850" ;
      ecrm:P78_is_identified_by "1850"]
```

**Comment by rtroncy** [comment]
A time span should have a start and an end (otherwise, it is not a span). For the implementation, we should ultimately end up using the xsd datatypes, this is what SPARQL engines can manipulate, compare, order, etc.

Consequently, I don't see what value brings the type E50 Date. Ultimately, you will also not find a better representation of time than what OWL Time is doing.

**Comment by pierrechoffe** [comment]
OK, this was just to let you know, but you are right, there is no real added value.

**Comment by pasqLisena** [comment]
Closed because moved to marc2rdf
