### ISSUE TITLE
Nouvelle release des données: sameAs manquant

### ISSUE THREAD

**Issue by delahousse** [DOREMUS-ANR/knowledge-base#29]
Nous avions des sameAs sur Bethoven, elles n'existent plus dans la nouvelle version

**Comment by rtroncy** [comment]
@delahousse J'ai renommé cette issue (c'est important de donner des titres et des descriptions précises car on ne s'y retrouve plus après quand il s'agit de chercher dans github)

Tu peux donner les URIs des ressources pour lesquelles tu penses qu'il manque des sameAs ? Quel sameAs manque-t-il exactement qu'il y avait avant ?

**Comment by delahousse** [comment]
http://data.doremus.org/artist/6963af5e-b126-3d40-a84b-97e0b78f5452

Mais en revenant dessus je vois les alignements que nous avions avant la release. J'ai du les rater tout à l'heure.

ok pour les noms des issues
