### ISSUE TITLE
[MoP] Mapping "unspecified" labels

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#3]
Simpler for me explaining with an example.

In MARC file, you can find as medium of performance `orchestra`.
In the vocabulary, there is `orchestra - unspecified`, that conceptually should be the same.

The String2URI fails in this case.

Probably this problem will disappear when we will complete the alignment for the MoP (so more labels will be available). But we should keep in mind this possible issue.

**Comment by rtroncy** [comment]
For the medium of performances, the source data in MARC makes use of labels or of codes? Does this vary depending if it comes from Philharmonie or BnF? In your example, this was Intermarc or Unimarc?
I agree, when the vocabulary will be aligned and consolidated, the problem should be resolved but this is useful to keep it in mind.

**Comment by pasqLisena** [comment]
> For the medium of performances, the source data in MARC makes use of labels or of codes? Does this vary depending if it comes from Philharmonie or BnF? In your example, this was Intermarc or Unimarc?

Both PP and BnF, both Intermarc and Unimarc, make use of labels in French (actually the problem was between `orchestre` and `orchestre - non spécifié`).

**Comment by pasqLisena** [comment]
As proposed by @marie-ototoi, we can remove the `- unspecified` part, because we defined broader/narrower relationship (see #2 ).
