### ISSUE TITLE
Gestion des dates et intervales

### ISSUE THREAD

**Issue by delahousse** [DOREMUS-ANR/knowledge-base#30]
Dans la nouvelle base il y a des changements dans la gestion des dates, j'ai qq remarques.
- pour la propriété P198i_was_born  on  a une valeur 1770-01-01, ce qui n'est pas la date de naissance mais la désignation de 1770. Je pense qu'il est plus propre et accepté par le format dateTime d'indiquer 1770 qui indique bien l'interval de l'année 1770. Dans le cas contraire on aura du mal a savoir qui est vraiment né le 1770-01-01
- pour la création d'une oeuvre on utilise E52_Timespan avec les propriétés P79 beginning is qualified by valeur 1801-01-01  et P80 end is qualified by 1801-12-31. C'est juste d'un point de vue connaissance, c'est bien dans cet interval avec un début et une fin, mais si on pouvait utiliser une propriété qui aurait comme valeur 1801 ce serait plus pratique. L'ontologie Time supporte bien cette gestion des intervals ou l'on indique soit une année, soit une vraie date de début et fin.

**Comment by rtroncy** [comment]
Is this not a duplicate of the issue #28 ?

**Comment by delahousse** [comment]
it is not a duplicate but it is in the same thread.
I move it in issue #28
