### ISSUE TITLE
Alternate French name "Ut" for "Do" in the Keys controlled vocabulary

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#32]
Should we add "Ut < anything >"@fr as `skos:alternateLabel` for "Do < anything >"@fr?
e.g.  "Ut majeur" for ["Do majeur"](http://data.doremus.org/vocabulary/key/c).

In [wikipedia](https://fr.wikipedia.org/wiki/Do_majeur), they suggest it as alternative.

**Comment by pierrechoffe** [comment]
Definitely !
