### ISSUE TITLE
Connect the catalogue vocabulary to artists

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#35]
Currently the catalogue vocabulary contains the reference to the artist as a string.

```ttl
<http://data.doremus.org/vocabulary/catalog/086> a modsrdf:ModsResource ;
    modsrdf:identifier "K",
        "KV" ;
    modsrdf:subjectName "MOZART, WOLFGANG AMADEUS (1756-1791)" ;
    owl:sameAs <http://catalogue.bnf.fr/ark:/12148/cb43076262w/PUBLIC> .
```

It could be useful connect it directly to the artist URI. It will be connected through [`modsrdf:subject`](http://www.loc.gov/standards/mods/modsrdf/v1/#subject) (but it is declared as abstract) or [`modsrdf:subjectComplex`](http://www.loc.gov/standards/mods/modsrdf/v1/#subjectComplex), keeping anyway the `modsrdf:subjectName` as is.

```ttl
<http://data.doremus.org/vocabulary/catalog/086> a modsrdf:ModsResource ;
    modsrdf:identifier "K",
        "KV" ;
    modsrdf:subjectName "MOZART, WOLFGANG AMADEUS (1756-1791)" ;
    modsrdf:subjectComplex <http://data.doremus.org/artist/4802a043-23bb-3b8d-a443-4a3bd22ccc63> ;
    owl:sameAs <http://catalogue.bnf.fr/ark:/12148/cb43076262w/PUBLIC> .
```

**Comment by pierrechoffe** [comment]
Excellent !

**Comment by rtroncy** [comment]
Doing so, would mean that ```<http://data.doremus.org/artist/4802a043-23bb-3b8d-a443-4a3bd22ccc63>``` becomes a ```madsrdf:ComplexSubject``` which is not really intended. You would instead expect that this resource is of ```madsrdf:Name``` (i.e. SimpleType rather than a ComplexType).

Why do you use the ```modsrdf``` prefix and not the ```madsrdf``` one?

**Comment by pasqLisena** [comment]
> Why do you use the modsrdf prefix and not the madsrdf one?

The default prefix for MODS is `modsrdf` (see [docs](http://www.loc.gov/standards/mods/modsrdf/v1)). MADS is sometimes used for ranges in MODS.
i.e. `mads:subjectName` does not exist, for example

> Doing so, would mean that <http://data.doremus.org/artist/4802a043-23bb-3b8d-a443-4a3bd22ccc63> becomes a madsrdf:ComplexSubject which is not really intended. You would instead expect that this resource is of madsrdf:Name (i.e. SimpleType rather than a ComplexType).

What about using another property? You know anyone that suits the case from Dublin Core?

**Comment by rtroncy** [comment]
> What about using another property? You know anyone that suits the case from Dublin Core?

+1 for using another property. I think that either [`foaf:primaryTopic`](http://xmlns.com/foaf/spec/#term_primaryTopic) or [`dc:subject`](http://dublincore.org/documents/dcmi-terms/#elements-subject) would be appropriate.

The full example could be something like:
```ttl
<http://data.doremus.org/vocabulary/catalog/086> a modsrdf:ModsResource ;
    modsrdf:identifier "K",
        "KV" ;
    modsrdf:subjectName "MOZART, WOLFGANG AMADEUS (1756-1791)" ;
    dc:subject <http://data.doremus.org/artist/4802a043-23bb-3b8d-a443-4a3bd22ccc63> ;
    owl:sameAs <http://catalogue.bnf.fr/ark:/12148/cb43076262w/PUBLIC> .
```
