### ISSUE TITLE
ISNI wrong wikipedia URI

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#36]
Retrieving the info from ISNI API, we realised that some wikipedia links are messy.
2 cases:
- the name contains a dash `-` [Lars-Erik Larsson](http://data.doremus.org/artist/9003abb1-f722-3891-a40b-e5f8fad9ca92)
  - the wikipedia URI is trunked before the dash (e.g. http://en.wikipedia.org/wiki/Lars)
  - see [ISNI page](http://www.isni.org/isni/0000000117785359) open _Notes_ tab
- homonyms (the two [Peter Cornelius](http://data.doremus.org/describe/?url=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPeter_Cornelius_%28opera_singer%29)
  - ISNI contains references to multiple wikipedia pages that in facts describe different persons
  - i.e. https://en.wikipedia.org/wiki/Peter_Cornelius_(opera_singer) and http://en.wikipedia.org/wiki/Peter_Cornelius
  - see [ISNI page](http://www.isni.org/isni/0000000121396655) open _Notes_ tab

Should we signal this cases to ISNI?

**Comment by rtroncy** [comment]
To be clear, those cases are incorrect alignments made by ISNI (incorrect alignments to Wikipedia). Who is maintaining ISNI? What is the procedure to report incorrect alignments or mistakes in the data? / cc @delahousse @FLERESCHE

**Comment by FLERESCHE** [comment]
Bonjour

La base publique isni.org permet de signaler, sur chaque notice, une erreur dans les données (boîte jaune à gauche de la notice). Ces signalements sont pris en charge par la British Library (3 semaines par mois) et la BnF (1 semaine par mois)), membres de la Quality team ISNI internationale.

Pour faire un signalement "en masse" (si beaucoup d'ISNI sont concernés), il  est possible d'envoyer un fichier à "isni@bnf.fr" et "isni.qt@bl.uk".
Bien cordialement
Françoise

**Comment by pasqLisena** [comment]
> Pour faire un signalement "en masse" (si beaucoup d'ISNI sont concernés), il  est possible d'envoyer un fichier à "isni@bnf.fr" et "isni.qt@bl.uk".

I think we should sent an email, I will prepare it

**Comment by pasqLisena** [comment]
I created a [table](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/data/wrong_artist_matches.tsv) with the wrong matches. I wrote to ISNI putting you in copy

**Comment by rtroncy** [comment]
Can we close this issue now @pasqLisena that ISNI has replied?

**Comment by pasqLisena** [comment]
I will close it during the next export (file in the [data folder](https://github.com/DOREMUS-ANR/knowledge-base/tree/master/data) should be regenerated).
