### ISSUE TITLE
[Keys] Use more transparent URIs and include some alignments when possible

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#4]
In the [keys vocabulary](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/key.ttl), we have records in this format

``` turtle
<http://data.doremus.org/vocabulary/key/2> a skos:Concept ;
    skos:prefLabel "Do majeur"@fr ;
    skos:editorialNote "unimarc: c"@fr ;
    skos:prefLabel "C Major"@en-us , "C Major"@en-gb , "Do maggiore"@it , "Do mayor"@es , "C Dur"@de ;
    skos:inScheme <http://data.doremus.org/vocabulary/key> .
```

I propose to change the URI on the base of the UNIMARC code:

``` turtle
<http://data.doremus.org/vocabulary/key/c>
```

---

Moreover, I put also attention on the MusicOntology version of the [keys vocabulary](http://purl.org/NET/c4dm/keys.owl). I put an example in n3 for readability.

``` turtle
keys:CMajor a keys:Key ;
    keys:mode "major"^^xsd:string ;
    keys:tonic keys:C ;
    keys:wikipedia "http://en.wikipedia.org/wiki/C_major"^^xsd:anyURI .
```

Mode and tonic are useful information.  It is foreseen an alignment to this vocabulary?

**Comment by rtroncy** [comment]
+1 for making the URIs more transparent and for adding alignments when necessary

**Comment by rtroncy** [comment]
Was the .ttl modified by hand or did you made some modifications to other resources as well (speadsheet? open refine project?)

**Comment by pasqLisena** [comment]
Open Refine.

I saved the new project on Google Drive (modelisation/referetiels/mise en commun).
