### ISSUE TITLE
[Mop Diabolo] Link to GeoNames

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#42]
Replace the strings of the places (in `dcterms:coverage`) with the link form GeoNames.
 
Example: https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/mop-diabolo.ttl#L749

**Comment by rtroncy** [comment]
+1 ! The "how" is important ... automatically with a validation workflow? Do you know how you will handle this?

**Comment by pasqLisena** [comment]
The "how" is through the API of GeoNames :)
I think I am going to integrate them in the "string2uri" module.

They are [not so many](http://data.doremus.org/sparql?default-graph-uri=&query=select+DISTINCT+%3Fo+where+%7B+%3Fs+dct%3Acoverage+%3Fo+%7D&format=text%2Fhtml&timeout=0&debug=on), so we can double check directly the differences in labels.
