### ISSUE TITLE
[MoP] Terms

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#45]
`band magnetique` ([usages](http://data.doremus.org/fct/facet.vsp?qxml=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%20%3F%3E%3Cquery%20inference%3D%22%22%20same-as%3D%22%22%20view3%3D%22%22%20s-term%3D%22%22%20c-term%3D%22%22%20agg%3D%22%22%3E%3Ctext%3Eband%20magn%C3%A9tique%3C%2Ftext%3E%3Cview%20type%3D%22text-d%22%20limit%3D%2220%22%20offset%3D%22%22%20%2F%3E%3C%2Fquery%3E)) is an `altLabel` for [`bande magnetique`](http://data.doremus.org/vocabulary/iaml/mop/eta)?

**Comment by ccecconi** [comment]
It's a mistake. This should'nt be in our data. Just keep "bande magnétique"
