### ISSUE TITLE
[MoP] Modification regarding language code and editorial notes

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#5]
- [x] **1 Return "pinyin" back to `oth`.**

on line 1355 of mediumofperformace_utf8.xls, it is specified the language “pinyin” (probably added by us). The note specifies that is a transliteration of Chinese (https://en.wikipedia.org/wiki/Pinyin), but the code “pny” refers actually to a language from Cameroon (https://en.wikipedia.org/wiki/Pinyin_language). My proposal is to replace it with “zhx“, or with "zho” (see https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) or to remove that code.

---
- [x] **2 Take a decision about the editorialNote**
- In the excel file, it is just a flag (t/f).
- The data currently published by IFLA states: "German term is preferred globally" [example](http://iflastandards.info/ns/unimarc/terms/mop/bah)
- @marie-ototoi interpreted as "Original term for this concept : Alphorn (german)"
- @pasqLisena interprets it as "use your language preferred, but if it does not exist, use the globally preferred one"
- We asked to Massimo (waiting for an answer).

---
- [x] **3 Removing (or not?) the "unspecified" label**

See #3 .

**Comment by marie-ototoi** [comment]
Pasquale, 
I don't think "original language" is  the right interpretation either, the thing is stating that "a language is globally preferred" does not make sense
- first in the original database it is a specific term (in a specific language) that is flagged, not the language
- then whatever this flag really means, "globally preferred" is not understandable

**Comment by pasqLisena** [comment]
@marie-ototoi we agree :)
Are you still waiting for a clarification from Massimo on this point, right?

**Comment by marie-ototoi** [comment]
Yes, he is on holidays, so this would be in October, but it is only a note, so it should not delay the alignment work.

**Comment by VladimirAlexiev** [comment]
The correct lang tag is zh-Latn-pinyin:
- IANA uses 2-letter codes where available
- Latn indicates the script
- pinyin indicates the transliteration method

See
- http://vocab.getty.edu/doc/#GVP_Language_Tags
  -[IANA tags](https://docs.google.com/spreadsheets/d/1M1yv9aBUmc-NyCJX69vOLUmH2uIglSwmDwgRgByI1AI/edit#gid=2001354273) obtained with the script described in the above link
