### ISSUE TITLE
Links from Isni to MusicBrainz

### ISSUE THREAD

**Issue by kgtodorov** [DOREMUS-ANR/knowledge-base#50]
@TheMarmottin 
4319 links to MusicBrainz that should be added on DOREMUS artists (identified by Jérôme Roy  through the  VIAF identifiers, restricting to doremus ID with no MB link):

https://loujine.github.io/musicbrainz-dataviz/doremus.html

[source page](https://github.com/loujine/musicbrainz-dataviz/blob/master/docs/doremus.html) - [jupyter notebook](https://github.com/loujine/musicbrainz-dataviz/blob/master/24-doremus.ipynb) with the process ([html version](https://loujine.github.io/musicbrainz-dataviz/24-doremus.html))

**Comment by pasqLisena** [comment]
It would be worth to convert that [table](https://loujine.github.io/musicbrainz-dataviz/doremus.html) (does a csv version exists?) in rdf, in order to be uploaded in the triplestore.

**Comment by TheMarmottin** [comment]
Well there is a CSV version now. I'm going to work on converting it in rdf, it should'nt take long.

**Comment by TheMarmottin** [comment]
[There it is.](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/data/isni/viaf_mb_mus_artists.rdf) I only wrote the ids, not the names, let me know if they are needed. I'll get working on modifying the actual artists files.

**Comment by pasqLisena** [comment]
Great :)
Names are not required, they are already in the triplestore.

> I'll get working on modifying the actual artists' files.

What do you mean?

**Comment by TheMarmottin** [comment]
I meant editing the 49 artists_x.ttl files, to add the sameAs property to their corresponding MusicBrainz id (for the ~4k artists that are concerned)

**Comment by TheMarmottin** [comment]
Oh by the way, I noticed that quite a lot of these artists have their VIAF id defined twice, such as this one : 
```turtle
doremus_artist:00272365-4985-3346-a47c-6f7be65190b5 owl:sameAs viaf:46477062;
      owl:sameAs <http://viaf.org/viaf/46477062>.
```
Is that intended ? If not, I can erase one of the two, since i'm going to parse all the artists anyway, might as well do it in one run.

**Comment by rtroncy** [comment]
Don't do this @TheMarmottin. This is unnecessary. This is better to maintain original files close to the source data and a sameAs file

**Comment by TheMarmottin** [comment]
Very well then :)

**Comment by pasqLisena** [comment]
so is this task complete? can we close the issue?

**Comment by rtroncy** [comment]
Almost.  @pasqLisena Can you remind us how the artists_x files in the [folder](https://github.com/DOREMUS-ANR/knowledge-base/tree/master/data/isni) are generated? And why some descriptions contain two equal sameAs links to the same VIAF URI?

**Comment by pasqLisena** [comment]
> Can you remind us how the artists_x files in the folder are generated?

They have been generated by a script that interrogates isni. Anyway they will be no more necessary (because of the new algorithm).

> And why some descriptions contain two equal sameAs links to the same VIAF URI?

Eventually, the viaf id can be expressed in 2 different part of the isni record. If they are coherent, I would not consider this a problem.

**Comment by rtroncy** [comment]
Indeed, this folder will not be loaded in the triple store since the new strategy will directly look into isni to generate doremus artist URI. The [sameAs file](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/data/isni/viaf_mb_mus_artists.rdf) created by @TheMarmottin is useful and should be loaded to add more links to music brainz.
@pasqLisena Should you clean up the repo and delete those isni files?
