### ISSUE TITLE
SKOS-ify 4 new controlled vocabularies

### ISSUE THREAD

**Issue by ccecconi** [DOREMUS-ANR/knowledge-base#52]
- [x] Responsibility of performers: https://docs.google.com/spreadsheets/d/1XgjBsAXja42BQlEU4pRquaz87erpkxrhXVVJDn7FOX4/edit#gid=623392783
- [x] Playing Speed: https://docs.google.com/spreadsheets/d/1Px7nxFd03Z08XFElD0l3QEvtE7yy-6UmVbRNJkDZW8c/edit#gid=1037416538
- [x] Types of Recording Equipment: https://docs.google.com/spreadsheets/d/1HkZ_kBvGRgIjwKEphcbazeyEMwNsg5HeIj-ShV45w1s/edit#gid=453347354
- [x] Performer status: https://docs.google.com/spreadsheets/d/1fYVdqx2o8FnptnxQrFYoodFX9av_1bXbeK0rmwiJYpk/edit#gid=0

Pasquale, we didn't change everything in the metadata tab. Please, look at it.

**Comment by rtroncy** [comment]
@ccecconi Quel est le prefLabel des concepts 'acoustique' et 'électrique' (lignes 6 et 7 de https://docs.google.com/spreadsheets/d/1HkZ_kBvGRgIjwKEphcbazeyEMwNsg5HeIj-ShV45w1s/edit#gid=453347354) ?

**Comment by ccecconi** [comment]
Les preflabel sont bien acoustique et electrique mais ils sont des termes spécifiques d'analogiques. La 2e colonne était un reliquat de l'ancienne mise en page. C'est corrigé.

**Comment by ccecconi** [comment]
- Performer status est également terminé : https://docs.google.com/spreadsheets/d/1fYVdqx2o8FnptnxQrFYoodFX9av_1bXbeK0rmwiJYpk/edit#gid=0
