### ISSUE TITLE
SKOS-ify 5 new controlled vocabularies

### ISSUE THREAD

**Issue by ccecconi** [DOREMUS-ANR/knowledge-base#53]
We finished 5 new vocabularies : 
- Colour content : https://docs.google.com/spreadsheets/d/1ft-TLVkkQFlIqJx6j7lLH6buZl99NV6U8D5r3awDflw/edit#gid=883914976
- Types of identifier : https://docs.google.com/spreadsheets/d/1ritEP-y3b3nO8OXTjpPkFbzjFx7nkWKL2LU_v5u8Kp4/edit#gid=747449586
- Carrier types : https://docs.google.com/spreadsheets/d/1rkpq0FnH3MTp4kJ_rw1vCWUWeRLupN_vL6OVB_JZYfA/edit#gid=2103668330
- Sound spatialization techniques : https://docs.google.com/spreadsheets/d/1iBMWWbZqoUvNnv61FWhYIX31DA1a_HzhtP5XRXBYJ2s/edit#gid=294813549
- Noise reduction techniques : https://docs.google.com/spreadsheets/d/1UPn5hZXRZFICOYIph-KdJEaqOiQWH9mzgxsRcwtdERU/edit#gid=706989854 (Only in english.  We are not sure how to translate in french these categories of techniques).

As usual, Pasquale could youhave a look at the metadata sheets ?

We decided not to create a new vocabulary for the types of musical scores. We will only use the one of UNIMARC : http://metadataregistry.org/concept/list/vocabulary_id/334.html

We also descided not to create a vocabulary dedicated to types of title. It's too library-oriented.

**Comment by pasqLisena** [comment]
closed in fb80e6f
