### ISSUE TITLE
Vocabulaire "Mode de représentation/exécution" à convertir en SKOS

### ISSUE THREAD

**Issue by ccecconi** [DOREMUS-ANR/knowledge-base#54]
https://docs.google.com/spreadsheets/d/1UCXCcPqBuK3qzEYrELzCZlUUghzvlo6k1d0l9DzOiNc/edit#gid=0

**Comment by rtroncy** [comment]
Est-ce que ce vocabulaire est utilisé dans les règles de mappings ?

**Comment by ccecconi** [comment]
Oui, mais ce n'est pas un élément essentiel.
