### ISSUE TITLE
Visualisation des vocabulaires contrôlés avec SKOSMOS

### ISSUE THREAD

**Issue by TLM-CIMU** [DOREMUS-ANR/knowledge-base#56]
Pour visualiser avec Skosmos chacun des vocabulaires contrôlés de façon indépendante, il est nécessaire d'accéder à un graphe nommé isolant chaque vocabulaire.
Dans le graphe tel qu'il a été créé, on ne dispose que du graphe nommé http://data.doremus.org/vocabulary.

Il faudrait disposer d'un graphe nommé par vocabulaire contrôlé.
Ci-dessous la liste des graphes nommés à définir et construire.

http://data.doremus.org/vocabulary/carrier
http://data.doremus.org/vocabulary/color_content
http://data.doremus.org/vocabulary/derivation
http://data.doremus.org/vocabulary/function
http://data.doremus.org/vocabulary/id
http://data.doremus.org/vocabulary/key
http://data.doremus.org/vocabulary/level
http://data.doremus.org/vocabulary/mode
http://data.doremus.org/vocabulary/noise_reduction
http://data.doremus.org/vocabulary/performance_condition
http://data.doremus.org/vocabulary/performer_status
http://data.doremus.org/vocabulary/playing_speed
http://data.doremus.org/vocabulary/recording_equipment
http://data.doremus.org/vocabulary/responsibility
http://data.doremus.org/vocabulary/spazialization (sic)
http://data.doremus.org/vocabulary/technique
http://data.doremus.org/vocabulary/work_type

Concernant les genres :
http://data.doremus.org/vocabulary/diabolo/genre
http://data.doremus.org/vocabulary/iaml/genre
http://data.doremus.org/vocabulary/redomi/genre
http://data.doremus.org/vocabulary/itema3/genre
http://data.doremus.org/vocabulary/itema3/genre/musdoc

Concernant les "mop" :
http://data.doremus.org/vocabulary/diabolo/mop
http://data.doremus.org/vocabulary/iaml/mop
http://data.doremus.org/vocabulary/itema3/mop
http://data.doremus.org/vocabulary/redomi/mop

Concernant le vocabulaire des catalogues, on peut créer le graphe nommé http://data.doremus.org/vocabulary/catalog

**Comment by TLM-CIMU** [comment]
Les vocabulaires MIMO (thésaurus des instruments de musique et classification H&S) étant aussi chargés dans votre entrepôt, j'aimerais qu'un graphe nommé désignant chacun de ces vocabulaires soit créé (http://www.mimo-db.eu/InstrumentsKeywords et http://www.mimo-db.eu/HornbostelAndSachs) : cela me permettra de tester Skosmos en connexion avec des entrepôts Virtuoso différents. Je dispose d'une version de ces vocabulaires sur un entrepôt installé à la PP mais la connexion avec Skosmos ne fonctionne pas totalement pour des questions de version/configuration de Virtuoso.

**Comment by TLM-CIMU** [comment]
Petite précision liée à mon expérience de Skosmos déjà appliqué aux vocabulaires MIMO : 
si, pour chaque vocabulaire, on crée un graphe nommé <http://data.doremus.org/vocabulary/xxx> (xxx : nom du vocabulaire), il faudra que dans ce vocabulaire existe un ConceptScheme clairement identifié par une URI du type <http://data.doremus.org/vocabulary/xxx#> ou <http://data.doremus.org/vocabulary/xxx/yyy> (yyy nom spécifique au ConceptScheme)

**Comment by TLM-CIMU** [comment]
Thanks a lot Pasquale. I'll keep you informed of my further experiments.
Thierry

**Comment by pasqLisena** [comment]
Wait a bit :) some issues in loading

**Comment by TLM-CIMU** [comment]
Ok !
