### ISSUE TITLE
[DIABOLO] Problem with the 'hang' instrument label

### ISSUE THREAD

**Issue by rtroncy** [DOREMUS-ANR/knowledge-base#57]
Pointed out by Jérôme Roy (MusicBrainz):

We have created this very long URI: http://data.doremus.org/vocabulary/diabolo/mop/le_joueur_de_hang_pose_generalement_linstrument_sur_ses_genoux_pour_jouer._il_fait_ensuite_resonner_le_hang_en_tapant_dessus_avec_la_main_et_les_doigts._linstrument_peut_se_jouer_a_deux_mains_et_permet_alors_datteindre_plusieurs_notes and the label of this instrument can probably be shorter.

What is also the difference with http://data.doremus.org/vocabulary/diabolo/mop/hang_(rohner-scharer)?

**Comment by pasqLisena** [comment]
This is the result of a wrong placement of text fields in the source excel.

In facts, that long string is a comment for the concept that you correctly spotted and pointed

**Comment by loujine** [comment]
Thanks. Next time I'll open the ticket directly (not sure what was the correct project)
