### ISSUE TITLE
[Derivation] Transparent URIs and translations.

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/knowledge-base#6]
I think that also the derivation vocabulary should have transparent URIs (like we did with keys in #4 ).
### New uris

We should base on the english term (that is almost everywhere similar to the french one also).

Example:

``` ttl
<http://data.doremus.org/vocabulary/derivation/11> a skos:Concept ;
    skos:prefLabel "Réorchestration"@fr , "Reorchestration"@en , "Riorchestrazione"@it , "Reorchestration"@de ;
```

will gain as new URI

``` ttl
<http://data.doremus.org/vocabulary/derivation/reorchestration>
```
### Missing translations

Some translations (in particular for 3 concepts) are missing.

In the [spreadsheet](https://docs.google.com/spreadsheets/d/1eRnULs1Ke9zgsYtGLC4qZ5LITGYEIHUvKkrntaVPeLY/edit#gid=0):

> faut-il traduire les quelques concepts manquants + les définitions au moins en anglais ?

I can also manage them if needed.
### Wrong translation

Both derivation 1 (Arrangement) and 9 (Réduction) are labelled in english with "Arrangement".
The latter should be renamed as Reduction (see [wikipedia](https://en.wikipedia.org/wiki/Reduction_%28music%29)).
### Broader-narrower

Differently respect what we wrote on #1 (all nodes are TopConcepts), I think that broader-narrower relationship could be stabilished.

In particular I propose:

| Broader Term | Narrower term |
| --- | --- |
| Arrangement | Orchestration, Reduction |
| Transcription | Orchestration, Reduction |

Question: it is possible in SKOS to mark one concept as narrower of two other ones?

---

Sub-issues summary:
- [x] new transparent URI using English terms
- [x] add the 3 missing translations of 'Parodie', 'Reconstruction' and 'Réminiscence'
- [x] correct the wrong translation of 'Reduction'
- [x] derivation hierarchy

**Comment by rtroncy** [comment]
+1 for the new transparent URI using English terms.

+1 for adding the 3 missing translations of 'Parodie', 'Reconstruction' and 'Réminiscence'

+1 for correcting the wrong translation of 'Reduction'

Yes, in SKOS, you can multiple narrower / broader statements. @marie-ototoi Do you confirm you would like to see those relationships?

**Comment by marie-ototoi** [comment]
The best is to discuss this with the group at the next meeting, since Pasquale will be there. 
I added it to the program https://docs.google.com/spreadsheets/d/1cXd5oBG2iF8IiwIYplbSn_UkRG5TtEaCGHj-6X6BY20/edit#gid=0

**Comment by pasqLisena** [comment]
I added the missing translations on the [Google Sheet](https://docs.google.com/spreadsheets/d/18Upf6MC7BbCCRRhwlSywHc_yvPzp2M0-EHdlSTWR8yY/edit#gid=0). I added also some Italian `altLabel`.

My modification have the yellow bg, I would validate them at the meeting.
