### ISSUE TITLE
[MoP] indicate Script in the lang tag

### ISSUE THREAD

**Issue by VladimirAlexiev** [DOREMUS-ANR/knowledge-base#7]
[iaml.ttl#L82](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/iaml.ttl#L82):

``` ttl
skos:altLabel "karnyx"@el, "κάρνυξ "@el ;
```

But because the first label is in transliterated Greek, it should indicate the script like so:

``` ttl
skos:altLabel "karnyx"@el-Latn, "κάρνυξ "@el ;
```

**Comment by pasqLisena** [comment]
Actually, there are lots of cases like that. We should find an automatic way for detecting them.

Having a list of the languages which use the latin alphabet, we can mark with "-Latn" all the language tag that: 1. should use a different alphabet, AND 2. are using the latin one.

@VladimirAlexiev based on this [table](https://docs.google.com/spreadsheets/d/1M1yv9aBUmc-NyCJX69vOLUmH2uIglSwmDwgRgByI1AI/edit#gid=2001354273), can we use the _Suppress-Script_ column for retrieving the alphabet of each language?

**Comment by rtroncy** [comment]
I would only mark the resources that don't use the Latin alphabet.

**Comment by pasqLisena** [comment]
> I would only mark the resources that don't use the Latin alphabet.

I was not clear, added an _AND_ in the previous comment.
So, we will mark all the translitterated labels.

**Comment by VladimirAlexiev** [comment]
Yes, "suppress script' says which script it's preferable to suppress, because it's default for that language.
