### ISSUE TITLE
Two ConceptSchemes in iaml.ttl?

### ISSUE THREAD

**Issue by VladimirAlexiev** [DOREMUS-ANR/knowledge-base#8]
[iaml.ttl](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/iaml.ttl#L6211) has two concept schemes, eg

``` ttl
<http://iflastandards.info/ns/unimarc/terms/mop/cch> a skos:Concept ;
    skos:broader <http://iflastandards.info/ns/unimarc/terms/mop/c> ;
    skos:inScheme <http://iflastandards.info/ns/unimarc/terms/mop/> .

<http://iflastandards.info/ns/unimarc/terms/mop/c> a skos:Concept ;
    skos:topConceptOf <http://data.doremus.org/vocabulary/iaml/> .

<http://data.doremus.org/vocabulary/iaml/> 
  skos:hasTopConcept         <http://iflastandards.info/ns/unimarc/terms/mop/c>.
```

Is it really the intention to have two schemes? While not illegal, I think this will confuse existing TMS (thes mgmt systems). The only example I am aware of is EuroVoc which has 2 schemes for each concept (EuroVoc and a microthesaurus thereof). But above the situation is different.

I'd suggest to get rid of the /iaml scheme, or else to use only /iaml URLs for all concepts and get rid of the /mop scheme.

**Comment by pasqLisena** [comment]
Thank you @VladimirAlexiev!
This has been caused by a (clearly not completely performed) renaming of the schema. Going to fix it.
