### ISSUE TITLE
mode.ttl uses literal not URL for topConceptOf

### ISSUE THREAD

**Issue by VladimirAlexiev** [DOREMUS-ANR/knowledge-base#9]
[mode.ttl](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/mode.ttl#L11):

``` ttl
<http://data.doremus.org/vocabulary/mode/1> a skos:Concept ;
    skos:topConceptOf "http://data.doremus.org/vocabulary/mode" ;
```

A simple syntax mistake: the latter should be URL not literal.

Also, I think it's better to have a trailing slash in the scheme since then one can use prefix notation to refer to both concepts and the scheme (with empty local-name). Eg in turtle (but same applies to sparql):

``` ttl
@prefix doremus-mode: <http://data.doremus.org/vocabulary/mode/>.

doremus-mode: a skos:ConceptScheme.
doremus-mode:1 a skos:Concept; skos:inScheme doremus-mode: .
```

GVP uses this convention, and you use it eg in iaml.ttl

**Comment by VladimirAlexiev** [comment]
@pasqLisena Not fixed:
- Trailing slash is used inconsistently:

```
skos:topConceptOf <http://data.doremus.org/vocabulary/mode>  VS
skos:inScheme <http://data.doremus.org/vocabulary/mode/> 
```
- have you checked this for all schemes? (I read only the start of the commit, and it talks only about the /mode scheme)

Cheers!

**Comment by pasqLisena** [comment]
> have you checked this for all schemes? (I read only the start of the commit, and it talks only about the /mode scheme)

It is right, I checked only on the mode scheme. I am planning in the beginning of the next week a complete revision of them.
